import { Schema, model } from 'mongoose';
import constant from '../../../shared/constant';
const token = new Schema(
    {
        NFTId: { type: String, default: '' },
        NFTName: { type: String, default: '' },
        CollectionName: { type: String, default: '' },
        CollectionSymbol: { type: String, default: '' },
        Category: { type: String, default: '' }, // enums : galfiship , galficrew721 ,PlanetCollection721
        nftCategory: { type: String, default: null },
        nftType: { type: String, default: null },
        crewGender: { type: String, default: null },
        status: { type: Boolean, default: true },
        NFTOrginalImage: { type: String, default: '' },
        image_url: { type: String, default: '' },
        fileType: { type: String, default: '' },
        image_thumb_url: { type: String, default: '' },
        image_animation_url: { type: String, default: '' },
        NFTThumpImage: { type: String, default: '' },
        NFTOrginalImageIpfs: { type: String, default: '' },
        NFTThumpImageIpfs: { type: String, default: '' },
        NFTProperties: { type: Array, default: [] },
        NFTRoyalty: { type: String, default: '' },
        NFTCreator: { type: String, default: '' },
        NFTDescription: { type: String, default: '' },
        NFTQuantity: { type: String, default: '' },
        NFTOwnerDetails: [{ type: Schema.Types.ObjectId, ref: 'tokenowner' }],
        MetaData: { type: String, default: '' },
        MetaDataUrl: { type: String, default: null },
        CompressedFile: { type: String, default: '' },
        CompressedThumbFile: { type: String, default: '' },
        UnlockContent: { type: String, default: '' },
        ContractAddress: { type: String, default: '' },
        ContractType: { type: String, default: '721' },
        ContractName: { type: String, default: '' },
        CollectionNetwork: { type: String, default: '' },
        collectionAddress: { type: String, default: '' },
        HideShow: { type: String, default: '' },
        BuyType: { type: String, default: '' },
        reported: { type: Boolean, default: false },
        isPromotion: { type: String, default: 'false' },
        islegalalert: { type: String, default: 'false' },
        deleted: { type: Number, default: 1 },
        Owners: { type: Array, default: [] },
        likecount: { type: Number, default: 0 },
        ReportBy: [
            {
                Address: { type: String, default: '' },
                CustomUrl: { type: String, default: '' },
                Message: { type: String, default: '' },
            },
        ],
        RandomName: { type: String, default: '' },
        NonceHash: { type: String, default: '' },
        SignatureHash: { type: String, default: '' },
        next: { type: String, default: null },
        totalXP: { type: Number, default: 0 },
        level: { type: Number, default: 1 },
        missionAvailability: { type: Boolean, default: true },
        missionType: {
            type: String,
            enum: ['', 'explore', 'mining', 'combat', 'social'],
            default: ''
        }, // store the type of mission the ship is currently on (explore, mining, combat, social)
        isRecruite: { type: Boolean, default: true },
        collectionTypeId: { type: Schema.Types.ObjectId, ref: 'collectiontype' },
        collectionType: { type: String, default: null },
        crewType: { type: String, default: null },
        isLocked: { type: Boolean, default: false },
        // isSync: { type: Boolean, default: true },
        lastSync: {
            type: Date,
            default: Date.now,
        },
        hexId: { type: Number, default: null },
    },
    { timestamps: true },
);

module.exports = model(constant.TOKEN_DB, token);
